spring.application.name=employemanagement2


###################
#server details
####################
server.port=2323

############
#Data Base Related Information
#############
spring.datasource.driver-Class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/batch77
spring.datasource.username= root
spring.datasource.password=root


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true